---
- name: create octoprint account
  become: yes
  user:
    name: octoprint
    comment: Octoprint account
    groups: tty,dialout,video
    system: yes
    password_lock: yes
    home: /home/octoprint
