---
- become: yes
  block:
  - name: install needed tools
    apt:
      update_cache: yes
      pkg:
        - python-pip
        - python-dev
        - python-setuptools
        - python-virtualenv
        - python-pillow
        - git
        - libyaml-dev
        - build-essential

  - name: install octoprint software
    become_user: octoprint
    shell:
      chdir: /home/octoprint
      cmd: |
        virtualenv --system-site-packages .
        source bin/activate
        pip install pip --upgrade
        pip install octoprint
    args:
      executable: /bin/bash

  - name: enable system wide packages
    file:
      path: /home/octoprint/lib/python2.7/no-global-site-packages.txt
      state: absent

  - name: Create symbolic link for PIL package
    file:
      src: /usr/lib/python2.7/dist-packages/PIL
      dest: /home/octoprint/lib/python2.7/site-packages/PIL
      state: link

  - name: Create symbolic link for pillow package
    file:
      src: /usr/lib/python2.7/dist-packages/Pillow-5.1.0.egg-info
      dest: /home/octoprint/lib/python2.7/site-packages/Pillow-5.1.0.egg-info
      state: link

  - name: install plugins
    become_user: octoprint
    pip:
      virtualenv: /home/octoprint
      name:
        - https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/master.zip
        - https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/archive/master.zip
        - https://github.com/juniorRubyist/OctoPrint-OctoFlat/archive/master.zip
        - https://github.com/kanocz/octopi_eta_override/archive/master.zip
        - https://github.com/OllisGit/OctoPrint-FilamentManager/releases/latest/download/master.zip
        - https://github.com/OllisGit/OctoPrint-DeleteAfterPrint/releases/latest/download/master.zip
#        - https://github.com/OllisGit/OctoPrint-PrintJobHistory/releases/latest/download/master.zip
        - https://github.com/paukstelis/OctoPrint-Cancelobject/archive/master.zip
        - https://github.com/Renaud11232/OctoPrint-Resource-Monitor/archive/master.zip
        - https://github.com/agrif/OctoPrint-InfluxDB/archive/master.zip
        - https://github.com/juergenpabel/OctoPrint-Procastinator/archive/master.zip
        - https://github.com/ManuelMcLure/OctoPrint-WiFiStatus/archive/master.zip

