---
- become: yes
  block:
  - name: install needed tools
    apt:
      update_cache: yes
      pkg:
        - python3-pip
        - python3-all-dev
        - python3-setuptools
        - python3-virtualenv
        - git
        - libyaml-dev
        - build-essential
        - acl
        - libjpeg8-dev
        - libffi-dev

  - name: install octoprint software
    become: true
    become_user: octoprint
    shell:
      chdir: /home/octoprint
      cmd: |
        virtualenv --system-site-packages .
        source bin/activate
        pip3 install pip --upgrade
        pip3 install octoprint
    args:
      executable: /bin/bash

  - name: install plugins
    become_user: octoprint
    pip:
      virtualenv: /home/octoprint
      name:
#       Bed Visualizer
        - https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/master.zip
#       Cancel Objects
        - https://github.com/paukstelis/OctoPrint-Cancelobject/archive/master.zip
#       Continuous Print
        - https://github.com/smartin015/continuousprint/archive/refs/heads/master.zip
#       DeleteAfterPrint Plugin
        - https://github.com/OllisGit/OctoPrint-DeleteAfterPrint/releases/latest/download/master.zip
#       Firmware Updater
        - https://github.com/OctoPrint/OctoPrint-FirmwareUpdater/archive/refs/heads/master.zip
#       HomeAssistant Discovery
        - https://github.com/cmroche/OctoPrint-HomeAssistant/archive/master.zip
#       MQTT
        - https://github.com/OctoPrint/OctoPrint-MQTT/archive/master.zip
#       OctoFlat Theme
        - https://github.com/juniorRubyist/OctoPrint-OctoFlat/archive/master.zip
#       Octolapse
        - https://github.com/FormerLurker/Octolapse/archive/master.zip
#       Prusa ETA override Plugin
        - https://github.com/kanocz/octopi_eta_override/archive/master.zip
#       Prusa MMU
        - https://github.com/jukebox42/Octoprint-PrusaMMU/releases/latest/download/Octoprint-PrusaMmu.zip
#       Slicer Thumbnails
        - https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/archive/master.zip

