---
- become: yes
  block:
  - name: install needed tools
    apt:
      update_cache: yes
      pkg:
        - python3-pip
        - python3-all-dev
        - python3-setuptools
        - python3-virtualenv
        - git
        - libyaml-dev
        - build-essential
        - acl
        - libjpeg8-dev

  - name: install octoprint software
    become: true
    become_user: octoprint
    shell:
      chdir: /home/octoprint
      cmd: |
        virtualenv --system-site-packages .
        source bin/activate
        pip3 install pip --upgrade
        pip3 install octoprint
    args:
      executable: /bin/bash

  - name: install plugins
    become_user: octoprint
    pip:
      virtualenv: /home/octoprint
      name:
        - https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/master.zip
        - https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/archive/master.zip
        - https://github.com/juniorRubyist/OctoPrint-OctoFlat/archive/master.zip
        - https://github.com/kanocz/octopi_eta_override/archive/master.zip
        - https://github.com/OllisGit/OctoPrint-SpoolManager/releases/latest/download/master.zip
        - https://github.com/OllisGit/OctoPrint-DeleteAfterPrint/releases/latest/download/master.zip
#        - https://github.com/OllisGit/OctoPrint-PrintJobHistory/releases/latest/download/master.zip
        - https://github.com/paukstelis/OctoPrint-Cancelobject/archive/master.zip
        - https://github.com/Renaud11232/OctoPrint-Resource-Monitor/archive/master.zip
        - https://github.com/agrif/OctoPrint-InfluxDB/archive/master.zip

