---
- become: yes
  block:
  - name: install needed tools
    apt:
      update_cache: yes
      pkg:
        - python-pip
        - python-dev
        - python-setuptools
        - python-virtualenv
        - git
        - libyaml-dev
        - build-essential

  - name: install octoprint software
    become_user: octoprint
    shell:
      chdir: /home/octoprint
      cmd: |
        virtualenv –system-site-packages .
        source bin/activate
        pip install pip --upgrade
        pip install octoprint
    args:
      executable: /bin/bash

  - name: install plugins
    become_user: octoprint
    pip:
      virtualenv: /home/octoprint
      name:
        - https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/master.zip
        - https://github.com/paukstelis/OctoPrint-Cancelobject/archive/master.zip
        - https://github.com/OllisGit/OctoPrint-DeleteAfterPrint/releases/latest/download/master.zip
        - https://github.com/malnvenshorn/OctoPrint-FilamentManager/archive/master.zip
        - https://github.com/juniorRubyist/OctoPrint-OctoFlat/archive/master.zip
        - https://github.com/kanocz/octopi_eta_override/archive/master.zip
        - https://github.com/Renaud11232/OctoPrint-Resource-Monitor/archive/master.zip
