---
- become: yes
  block:
  - name: copy systemd service config
    copy:
      src: octoprint.service
      dest: /lib/systemd/system/octoprint.service

  - name: enable systemd service
    systemd:
      name: octoprint
      enabled: yes
      state: started

  - name: enable octoprint to restart itself
    copy:
      src: sudoers.conf
      dest: /etc/sudoers.d/octoprint
      mode: 0440
