---
#- hosts: iron-man.lan
#  roles:
#    - ssh
#    - ubuntu
#
#- hosts: prusa.lan
#  roles:
#    - ssh
#    - octoprint
#    - ubuntu

- hosts: docker_cluster
  roles:
    - ssh
    - docker-cluster
    - ubuntu

#- hosts: router.lan
#  roles:
#    - router

