---
- hosts: docker_cluster
  roles:
    - node_explorer
    - ssh
    - docker-cluster
    - ubuntu

- hosts: remote_server
  roles:
    - docker

- hosts: uatu.lan
  roles:
    - db-backup
    - ssh
    - ubuntu
    - docker
    - duplicity
    - node_explorer

- hosts: dymo
  roles:
    - ssh
    - cups-server
