---
#- hosts: iron-man.lan
#  roles:
#    - ssh
#    - ubuntu
#
#- hosts: prusa
#  roles:
#    - ssh
#    - octoprint
#    - ubuntu

- hosts: docker_cluster
  roles:
#    - node_explorer
#    - ssh
    - docker-cluster
#    - ubuntu
#
#- hosts: raspberry
#  roles:
#    - i2c-clock

#- hosts: router.lan
#  roles:
#    - router

#- hosts: iron-man
#  roles:
#    - ssh
