---
- hosts: prusa
  roles:
    - ssh
    - octoprint
    - ubuntu

- hosts: docker_cluster
  roles:
    - node_explorer
    - ssh
    - docker-cluster
    - ubuntu

#- hosts: raspberry
#  roles:
#    - i2c-clock

#- hosts: router.lan
#  roles:
#    - router

- hosts: remote_server
  roles:
    - docker

- hosts: uatu.lan
  roles:
    - db-backup
    - ssh
    - ubuntu
    - docker
    - duplicity
    - node_explorer


- hosts: laptop.lan
  roles:
    - node_explorer
