---
- name: install required packages
  apt:
    update_cache: yes
    pkg:
      - git
      - make
      - libx11-dev
      - libxft-dev
      - libxinerama-dev

- name: checkout
  shell:
    cmd: |
      mkdir -p ~/src
      cd ~/src
      git clone {{ dwm-repo }}

- name: build dwm
  make:
    chdir: ~/src/dwm

- name: copy xsession
  become: yes
  copy:
    src: usr/share/xsessions/dwm.desktop
    dest: /usr/share/xsessions/dwm.desktop

- name: copy icon
  become: yes
  copy:
    src: usr/share/icons/dwm.png
    dest: /usr/share/icons/dwm.png

- name: install dwm
  become: yes
  make:
    chdir: ~/src/dwm
    target: install
