---
all:
  children:
    server:
      hosts:
        prusa.lan:
          ansible_user: ubuntu
        iron-man.lan:
      children:
        docker_swarm:
          hosts:
            node-01.lan:
              docker_node: node-01
            node-02.lan:
              docker_node: node-02
            node-03.lan:
              docker_node: node-03
            node-x86.lan:
              docker_node: node-x86
              ansible_host: 192.168.50.186
              release: bionic
