---
all:
  hosts:
    prusa.lan:
      vars:
        ansible_user: ubuntu
    iron-man.lan:
  children:
    docker_swarm:
      hosts:
        node-01.lan:
          docker_node: node-01
        node-02.lan:
          docker_node: node-02
        node-03.lan:
          docker_node: node-03
