---
all:
  hosts:
    router:
      ansible_host: 192.168.50.2
      vars:
        ip: 2
        mac: 2c:b0:5d:4a:72:62
    bender:
      ansible_host: 192.168.50.3
    home-assistant:
      ansible_host: 192.168.60.100
    uatu:
      ansible_host: 192.168.50.106
    dymo:
      ansible_host: 192.168.50.109
    node-cluster:
      ansible_host: 192.168.50.151
    remote_server:
      ansible_host: 192.168.90.4
      ansible_become_password:
      ansible_user: ubuntu
  children:
    raspberry:
      hosts:
        dymo:
        uatu:
    lan:
      hosts:
        bender:
        home-assistant:

      children:
        docker_cluster:
          hosts:
            node-cluster:
    ubuntu:
      hosts:
        uatu:
    debian:
      hosts:
        dymo:
