---
all:
  hosts:
    prusa.lan:
    iron-man.lan:
    router.lan:
  children:
    docker_cluster:
      hosts:
        node-01.lan:
          ansible_host: 192.168.50.101
        node-02.lan:
          ansible_host: 192.168.50.102
        node-03.lan:
          ansible_host: 192.168.50.103
        node-x86.lan:
          ansible_host: 192.168.50.186
