---
all:
  hosts:
    router:
      ansible_host: 192.168.50.2
      vars:
        ip: 2
        mac: 2c:b0:5d:4a:72:62
    bender:
      ansible_host: 192.168.50.3
      vars:
        ip: 3
        mac: e0:3f:49:6f:03:c2

    home-assistant:
      ansible_host: 192.168.50.5
      vars:
        ip: 5
        mac: dc:a6:32:8b:7b:ab
        mac2: 6a:1b:c8:63:58:7a
    prusa:
      ansible_host: 192.168.50.6
      vars:
        ip: 6
        mac: b8:27:eb:96:f3:3f
        mac2: b8:27:eb:c3:a6:6a
#    rpi3-02:
    iron-man:
      ansible_host: 192.168.50.7
      vars:
        ip: 7
        mac: b8:27:eb:19:f8:0d
    rpi3a:
      ansible_host: 192.168.50.8
      vars:
        ip: 8
        mac: b8:27:eb:ff:2a:86
    kvm-bender:
      ansible_host: 192.168.50.11
      vars:
        ip: 11
        mac: dc:a6:32:f6:63:c1
    android-sgs9:
      vars:
        ip: 41
        mac: 24:18:1d:bc:fe:4f
    ipad:
      vars:
        ip: 42
        mac: b8:63:4d:b6:4c:bc
    node-01.lan:
      ansible_host: 192.168.50.101
      vars:
        ip: 101
        mac: dc:a6:32:03:6d:fa
    node-02.lan:
      ansible_host: 192.168.50.102
      vars:
        ip: 102
        mac: dc:a6:32:3c:0f:ff
    node-03.lan:
      ansible_host: 192.168.50.103
      vars:
        ip: 103
        mac: dc:a6:32:3c:1a:ec
    node-x86.lan:
      ansible_host: 192.168.50.186
      vars:
        ip: 186
  children:
    raspberry:
      hosts:
        node-01.lan:
        node-02.lan:
        node-03.lan:
    lan:
      hosts:
        router:
        bender:
        home-assistant:
        rpi3-01:
#        rpi3-02:
        iron-man:
        prusa:


      children:
        docker_cluster:
          hosts:
            node-01.lan:
            node-02.lan:
            node-03.lan:
            node-x86.lan: