---
all:
  hosts:
    router:
      ansible_host: 192.168.50.2
      vars:
        ip: 2
        mac: 2c:b0:5d:4a:72:62
    bender:
      ansible_host: 192.168.50.3
    home-assistant:
      ansible_host: 192.168.60.100
    laptop.lan:
      ansible_host: 192.168.50.29
    prusa:
      ansible_host: 192.168.50.6
    node-01.lan:
      ansible_host: 192.168.50.101
    node-02.lan:
      ansible_host: 192.168.50.102
    node-03.lan:
      ansible_host: 192.168.50.103
    node-04.lan:
      ansible_host: 192.168.50.104
    uatu.lan:
      ansible_host: 192.168.50.106
    node-x86.lan:
      ansible_host: 192.168.50.186
    remote_server:
      ansible_host:
      ansible_become_password:
      ansible_user: ubuntu
  children:
    raspberry:
      hosts:
        node-01.lan:
        node-02.lan:
        node-03.lan:
        node-04.lan:
    lan:
      hosts:
        router:
        bender:
        home-assistant:
        rpi3-01:
#        rpi3-02:
        iron-man:
        prusa:


      children:
        docker_cluster:
          hosts:
            node-01.lan:
            node-02.lan:
            node-03.lan:
            node-04.lan:
            node-x86.lan: