---
- become: yes
  block:
    - name: disable help in ubuntu
      when: ansible_distribution == "Ubuntu"
      file:
        path: /etc/update-motd.d/10-help-text
        mode: '0644'

    - name: install screenfetch
      apt:
        update_cache: yes
        pkg:
          - screenfetch

    - name: add screenfetch to motd
      copy:
        src: etc/update-motd.d/05-screenfetch
        dest: /etc/update-motd.d/05-screenfetch
        mode: '0755'
