---
- become: yes
  block:
    - name: check if help in motd exists
      stat:
        path: /etc/update-motd.d/10-help-text
      register: stat_result

    - name: disable help in ubuntu
      when:
        - ansible_distribution == "Ubuntu"
        - stat_result.stat.exists
      file:
        path: /etc/update-motd.d/10-help-text
        mode: '0644'

    - name: install neofetch
      apt:
        update_cache: yes
        pkg:
          - neofetch

    - name: add screenfetch to motd
      copy:
        src: etc/update-motd.d/05-neofetch
        dest: /etc/update-motd.d/05-neofetch
        mode: '0755'

    - name: uninstall screenfetch
      apt:
        update_cache: yes
        state: absent
        pkg:
          - screenfetch

    - name: remove screenfetch from motd
      file:
        path: /etc/update-motd.d/05-screenfetch
        state: absent
