---
- become: yes
  block:
    - name: clean packages
      apt:
        pkg:
          - snapd
          - cloud-init
          - lxd
          - lxd-client
        state: absent

    - name: disable ubuntu ads
      copy:
        src: etc/default/motd-news
        dest: /etc/default/motd-news
