---
- name: copy monitor script
  copy:
    src: monitor.sh
    dest: /config/scripts/monitor.sh
    mode: '0755'

- name: copy script for reseting modem
  copy:
    src: tplink_smartplug.py
    dest: /config/scripts/tplink_smartplug.py
    mode: '0755'

- name: setup cron task
  vars:
    ansible_connection: network_cli
    ansible_network_os: edgeos
  edgeos_config:
    lines:
      - set system task-scheduler task restartWan executable path /config/scripts/monitor.sh
      - set system task-scheduler task restartWan interval 5m

