---
- name: Create hostfile
  become: yes
  template:
    src: usr/local/sbin/check-docker.j2
    dest: /usr/local/sbin/check-docker
    mode: '0755'

- name: create cron
  become: yes
  cron:
    name: "check docker"
    minute: "*/15"
    job: "/usr/local/sbin/check-docker"