---
- become: yes
  block:
    - name: install heartbeat
      apt:
        update_cache: yes
        pkg:
          - heartbeat

    - name: copy configuration
      copy:
        src: etc/ha.d/ha.cf
        dest: /etc/ha.d/ha.cf

    - name: copy resources
      copy:
        src: etc/ha.d/haresources
        dest: /etc/ha.d/haresources
