---
- become: yes
  block:
  - name: "[Ubuntu] install nfs-client"
    when: ansible_distribution == "Ubuntu"
    apt:
      update_cache: yes
      pkg:
        - nfs-common

  - name: "[Arch] install nfs-client"
    when: ansible_distribution == "Archlinux"
    become: yes
    community.general.pacman:
      update_cache: yes
      name: nfs-utils

  - name: "[Generic] update rpc config"
    copy:
      src: lib/systemd/system/rpc-statd.service
      dest: /lib/systemd/system/rpc-statd.service

  - name: "[Generic] stop and disable rpc"
    systemd:
      name: rpc-statd
      state: stopped
      enabled: false

  - name: "[Generic] start and enable rpc"
    systemd:
      name: rpc-statd
      state: started
      enabled: true
