---
- become: yes
  block:
    - name: copy config
      copy:
        owner: root
        group: root
        mode: 0600
        directory_mode: yes
        src: etc/ssh
        dest: /etc

    - name: copy ha.d resource ssh-external
      copy:
        owner: root
        group: root
        mode: 0755
        src: etc/ha.d/resource.d/ssh-external
        dest: /etc/ha.d/resource.d/ssh-external

    - name: add systemd service
      copy:
        src: lib/systemd/system/sshd-external.service
        dest: /lib/systemd/system/sshd-external.service
